# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VX-uoTWybwWddSQ3SyhWwIoHVySvjD7p
"""

import pandas as pd

pd.read_csv("/content/delivery_delay.csv")

df=pd.read_csv("/content/delivery_delay.csv")

df

x=df.drop("Delivery_Delay",axis=1)

y=df["Delivery_Delay"]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression
logi = LogisticRegression(max_iter=1000)

logi.fit(x_train, y_train)

import pandas as pd

# Get column names from x_train
feature_names = x_train.columns

# Create a DataFrame from the input list with the correct column names
input_data = pd.DataFrame([[20,3,1,2,5,2,3,3,120,12,120]], columns=feature_names)

# Make the prediction
logi.predict(input_data)

logi.predict_proba(input_data)

logi.score(x_test,y_test)

from sklearn.metrics import recall_score

y_pred = logi.predict(x_test)
recall = recall_score(y_test, y_pred)
print(f"Recall Score: {recall}")

from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(logi, x_train, y_train, cv=5, scoring='recall')

print(f"Cross-validation Recall Scores: {cv_scores}")
print(f"Mean CV Recall Score: {cv_scores.mean():.4f}")
print(f"Standard Deviation of CV Recall Scores: {cv_scores.std():.4f}")

from sklearn.metrics import roc_curve, roc_auc_score, RocCurveDisplay
import matplotlib.pyplot as plt

# Get probabilities for the positive class
y_pred_proba = logi.predict_proba(x_test)[:, 1]

# Calculate AUC score
auc_score = roc_auc_score(y_test, y_pred_proba)
print(f"AUC Score: {auc_score:.4f}")

# Plot ROC Curve
fig, ax = plt.subplots(figsize=(8, 6))
RocCurveDisplay.from_estimator(logi, x_test, y_test, ax=ax)
plt.title('ROC Curve')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

from sklearn.tree import DecisionTreeClassifier

# Create a Decision Tree classifier with max_depth=2
dtc = DecisionTreeClassifier(max_depth=2, random_state=42)

# Train the model
dtc.fit(x_train, y_train)

print("Decision Tree Classifier (max_depth=2) created and trained.")

from sklearn.metrics import accuracy_score

# Make predictions on the test set using the Decision Tree Classifier
y_pred_dtc = dtc.predict(x_test)

# Calculate the accuracy score
accuracy_dtc = accuracy_score(y_test, y_pred_dtc)
print(f"Accuracy of Decision Tree Classifier: {accuracy_dtc:.4f}")

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20,10))
plot_tree(dtc, feature_names=x.columns, class_names=['No Delay', 'Delay'], filled=True, rounded=True)
plt.title("Decision Tree Classifier (max_depth=2)")
plt.show()

import.joblib

import joblib
joblib.dump(logi, 'logi.sav')

